### ISSUE TITLE
WindowsTerminal.exe Crash

### ISSUE THREAD

**Issue by Olenjan** [snowie2000/mactype#980] opened 2024-03-03 23:47 UTC
WindowsTerminal.exe crashes when starting a Default ConsoleApplication in Visual studio 2022.
WindowsTerminal.exe crashes in other use cases as well

Does not seem to consistently cause this issue - Some times after the restart everything is working as expected for a while.

MacType version:	2021.1 
MacTray version:	1.0.2021.1
MacType Tuner version:	1.0.2.361
Profile: Clean.Optimized.QD-OLED from https://github.com/snowie2000/mactype/issues/932#issuecomment-1598653839

EventViewer error log:
```
Faulting application name: WindowsTerminal.exe, version: 1.19.2402.26003, time stamp: 0x65dce3ea
Faulting module name: MacType64.Core.dll, version: 1.2021.507.1, time stamp: 0x6094e4a5
Exception code: 0xc0000005
Fault offset: 0x0000000000005ea9
Faulting process id: 0x0x486C
Faulting application start time: 0x0x1DA6DC38B8CC835
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe\WindowsTerminal.exe
Faulting module path: C:\Program Files\MacType\MacType64.Core.dll
Report Id: 83a1c2e6-3704-42a3-ad6c-11717139e886
Faulting package full name: Microsoft.WindowsTerminal_1.19.10573.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

Workaround: Add WindowsTerminal.txt exclusion in MacType.ini under [UnloadDll] section.

**Comment by snowie2000** [comment] 2024-03-04 01:48
Duplicate of #607 
update to the latest RC should fix the problem.

**Closed as completed by snowie2000** 2024-03-04 01:48 UTC
