### ISSUE TITLE
MacType causing random slient crash on Telegram Desktop

### ISSUE THREAD

**Issue by Jamesits** [snowie2000/mactype#271] opened 2017-04-25 05:21 UTC
Version: Windows 10 1703 15063.138, MacType 1.2016.904.0 with CTP_170307_W10 patch
Configration: Tray loading, [Config file](https://gist.github.com/Jamesits/6a58a1b08d5cd09a94a02f30ddaf0e13/f6ae51aa77c1345f404983531294cd7b338eff4b)

Telegram Desktop 1.0.29 (both installer version and UWP store version) crashes randomly.

![image](https://cloud.githubusercontent.com/assets/1297257/25369892/b2cb108c-29b9-11e7-9d6d-37fabbac507a.png)

**Comment by Jamesits** [comment] 2018-08-28 06:27
Cannot reproduce on 1.2017.628.0.

**Comment by sammilucia** [comment] 2018-08-28 06:31
Thanks so much @Jamesits 😊
Closing as resolved

**Comment by sammilucia** [comment] 2018-09-11 01:31
Thanks for your additional diagnostic work @Jamesits and for letting me know. I've added this to the list of known problems in #426. Since you've reinstalled Windows and the problem doesn't exist without MacType I've added it as a confirmed problem.

Have you tried just ignoring the exceptions and continuing running Telegram? Does it continue to work properly (other than the exceptions)?

**Comment by Jamesits** [comment] 2018-09-11 01:34
I've switched to Unigram (a 3rd party Telegram UWP impl) and it is affected too. I'm doing more experiments.

**Comment by Jamesits** [comment] 2018-09-11 01:54
It seems MacType is causing issues with all UWP programs written in WinRT XAML. Microsoft Edge randomly stopped responding (not responsive to all click events, but scrolling works fine; unable to recover webpage) after enabling it. 

MacType version:	1.2017.628.0
MacTray version:	1.0.5.2048
MacTuner version:	1.0.2.350

**Comment by snowie2000** [comment] 2018-09-11 02:02
Microsoft has reported to me a lot of crash issues (with bug reports pointing to easyhook), however, because they only collect basic stack traces instead of memory dumps, although I identified the specific line of the crash, it doesn't seem to be possible to crash at that line.
And I tried mactype on Windows 10, trying to reproduce some of the key API calls that cause the crash with no luck.
I reported the problem back to Microsoft and that's all for now. They said they will reach me again once their technical guys work it out, but they didn't.

**Comment by sammilucia** [comment] 2018-09-22 09:38
@Jamesits can you please try the latest beta https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 which has an updated EasyHook and let us know if the problem still occurs? Ty 😊

**Comment by Jamesits** [comment] 2018-09-23 13:51
@sammilucia The new beta version caused more halts on UWP apps than any version before... I experienced Explorer/Start menu stopped responding, Explorer failed to initialize taskbar, and Edge rendering process failure after minutes enabling the new version. Tried rebooting but nothing changes. I wanted to debug some processes but VS2017 is affected too. Can you give me some guidance on how to at least record a debug trace? I have no idea now.

**Comment by snowie2000** [comment] 2018-09-23 14:10
@Jamesits What loading mode are you using?
If you're using registry mode, try other modes instead as they offer an easier way to enable MacType for a single process so that you can do memory dump or things like that.

To create memory dumps for crashed applications, you can try methods mentioned in this thread:
https://stackoverflow.com/questions/30121822/how-to-generate-windows-memory-dump-when-application-crashes

**Comment by snowie2000** [comment] 2018-09-23 14:12
Plus, please disable mactype-patch before going any further as it will bring more uncertainty to problems.

**Comment by Jamesits** [comment] 2018-09-23 14:46
@snowie2000 I'm always using tray (standard) loading mode without Admin privileges. I haven't used mactype-patch. 

Thanks for the hint on getting a dump, but I need a way to debug the system when most windows are not responding or just inoperable...

**Comment by sammilucia** [comment] 2018-09-23 14:56
@Jamesits thanks for baring with us thru this... Three questions just to eliminate some things:
1. Have you tried a clean install of MacType following the beta2 instructions (https://github.com/snowie2000/mactype/releases)? 
2. Can you please try a plain ini like the attached
[No Hinting.zip](https://github.com/snowie2000/mactype/files/2408810/No.Hinting.zip)
3. Just for clarity, does everything stop responding only when UWP is running ... or even when UWP is not running?

**Comment by snowie2000** [comment] 2018-09-23 15:10
@Jamesits Please try tray mode with admin priviledge as the tray mode w/o admin priviledge is not well tested.

**Comment by snowie2000** [comment] 2018-09-23 15:14
One more hint. 
To debug when everything is inoperable, just add vs2017 and taskmgr to unloaddll list so that you always have a change to call out the task manager and start vs from there.

**Comment by Jamesits** [comment] 2018-09-23 15:15
@sammilucia 

1. This is a clean install. The OS is recently reinstalled (I formatted the disk because the filesystem failed, so there should be no problems from Windows upgrade process), and this is the first time this OS had MacType installed.

2. Tried the no hinting config:

* MacType tray immediately stopped responding
* Explorer restarts every few seconds
* Edge reports the page renderer process stopped responding; switching tabs not possible
* Task Manager seems to be working fine
* I didn't notice mouse input problems (When using [my own config](https://gist.github.com/Jamesits/6a58a1b08d5cd09a94a02f30ddaf0e13), the mouse stopped moving every few seconds)

3. At least some UWP applications stopped working for me. I don't know how to eliminate every UWP program in this version of Windows 10 since the explorer is part UWP.

**Comment by snowie2000** [comment] 2018-09-23 15:18
If you eventually failed to debug it yourself, please check your eventlog and see if there is anything worthy there.

**Comment by snowie2000** [comment] 2018-09-23 15:29
Looks like the crash report is not anything useful at all. A memory dump is necessary then. 

Also, according to the screenshot you provided in your first post, mactype is faulty before it loads its substantial part into the telegram.

**Comment by sammilucia** [comment] 2018-09-23 16:08
What's so strange is others don't seem to be having this issue (?), something may be different or unique on your Windows, so thanks for working thru this @Jamesits it's really helpful

**Comment by Jamesits** [comment] 2018-09-24 01:42
@sammilucia I think maybe because I have one 100% and one 200% screen connected? I'll fire up a VM and see if I can reproduce this problem.

(Have to go to a business trip, expect my result after a week :)

**Comment by snowie2000** [comment] 2018-09-25 00:56
@Jamesits You can try to only overwrite easyhook of the old install with the patched one to see if the crash persists.

Have a good day on your trip!

**Comment by sammilucia** [comment] 2018-10-19 12:11
Hi @Jamesits, can you please try the new beta4 https://github.com/snowie2000/mactype/releases/tag/v1.2018.10.19-beta4 and let us know if the problem is resolved. This includes the changes to easyhook.

**Comment by snowie2000** [comment] 2018-10-19 12:37
Ok, I think you need to grant full control permission to "everyone" to the installation folder.

**Comment by Jamesits** [comment] 2018-10-19 12:42
@snowie2000 granted. Now I can start via MacTray which I think have no actual use, and I cannot either stop, restart. Quitting MacTray after started will cause it to stop responding. I think something's wrong while starting.

**Comment by snowie2000** [comment] 2018-10-19 12:45
Did you run mactype as administrator?
If not, try it.

**Comment by Jamesits** [comment] 2018-10-19 13:01
@snowie2000 Tried running as Administrator.

Before launching MS Edge:
 * Can start/stop/restart
 * At least some fonts are being substituted (notably the IME and MacTray details dialog; but font of MacTray context menu is not substituted)
 * DirectWrite not working at all (enabled in config)

After launching MS Edge:
 * MacTray stopped responding
 * Edge render processes stopped responding at the first frame they draw

**Comment by Jamesits** [comment] 2018-10-19 13:30
* Can start
* Can stop, though a little bit slow (responds ~30s later)
* Can quit, but will still kill one or two edge render process
* Font substitution still only working for limited dialogs

**Comment by snowie2000** [comment] 2018-10-19 13:39
I may need to set up a win10 VM to test all the problems next monday.
Could you please try to extract the old mactray.exe from 2017.628 to see if can work with the new dlls correctly? So we can narrow down the problem to mactype or just the tray app.

**Comment by Jamesits** [comment] 2018-10-19 13:45
It behaves the same as the new MacTray.

**Comment by Jamesits** [comment] 2018-10-19 13:47
Also I've set up a few Windows 10 VMs but cannot really reproduce all the problems I'm currently experiencing. If you can't reproduce them too, maybe we can schedule a time to let you connect to my PC and have a look?

**Comment by snowie2000** [comment] 2018-10-19 13:49
So it's the problem with mactype.core then.
As I don't have any Windows10 machine available this weekend, I have to delay all the investigation and tests to the next week.

Does the previous beta work for you?

**Comment by Jamesits** [comment] 2018-10-19 13:53
No, it never worked after Windows 10 RS4. I have a VM running Windows 10 2016 LTSB and MacType 1.2017.628.0, and it worked really well.

**Comment by snowie2000** [comment] 2018-10-19 13:56
So it's a problem introduced by RS4. 
looks like a Vm running the specific version is a must to reproduced all the problems. sign....

**Comment by sammilucia** [comment] 2018-10-19 14:20
I can't reproduce with Win10 32-bit (1803)

James I don't think this is related but it would be useful to know Windows is in a consistent state on the PC you're having problems with. Have you tried a DISM restore?

**If you do this please ensure you have a backup.**

From an elevated cmd prompt do:
```
dism /online /cleanup-image /restorehealth
```
Which will check the Windows image (source files) is consistent. Once that's done do:
```
sfc /scannow
```
Which will verify the live Windows files are consistent.

You may need to do each command a few times until they complete without errors... if that's the case it's a good indication there were problems.

**Comment by Jamesits** [comment] 2018-10-19 14:28
Bad news is that I've tried VMs running RS4/RS5 but cannot reproduce the problem.

**Comment by snowie2000** [comment] 2018-10-19 14:31
edge is well known for its defense and Microsoft is keeping adding barriers to the edge so I believe the edge is the toughest process across the windows 10 os. 

Anyway try to exclude the edge process and see if the mactype is working well for your other programs  so that we can concentrate on the one specific program.

**Comment by sammilucia** [comment] 2018-10-19 14:34
Yes, I'm pretty sure it's not MacType, it's something to do with your Windows install. You can try the DISM and SFC I suggested above. I'd be surprised if this will fix it but it will eliminate a corrupt Windows install as the cause.

The new installer does go looking for EasyHk*.dll in a few locations (e.g. System32 and SysWOW) but it doesn't do a comprehensive search. You could use something like [SearchMyFiles](https://www.nirsoft.net/utils/search_my_files.html) to do a comprehensive search of your Windows folder for any left over MacType*.dll files or EasyHk*.dll files. If they are in your Windows folders (or in your Path)  anywhere, they will get loaded before the new MacType files.

**Comment by sammilucia** [comment] 2018-10-19 14:35
@snowie2000 yeah this is my problem with Win10 ... How are we supposed to maintain "known good" installs if it keeps modifying itself. It goes against basic engineering principles.

**Comment by snowie2000** [comment] 2018-10-19 14:42
We don't know. Nobody knows. It's called rolling update, or rolling bug - a bug that's rolling like a snowball - gets bigger on every roll. 
I'm just kidding. it's just that the win10 don't like my sound card and kills it every time I reboot. :haha

**Comment by snowie2000** [comment] 2018-10-19 15:06
Thank for your extraordinary unbelievable work. Before you start cloning your system to a VM, could you please take a minute and try to exclude edge to see if mactype is fully working for your other programs? 

By exclude, I mean writing to the unloaddll section.

**Comment by Jamesits** [comment] 2018-10-19 15:29
```
[UnloadDll]
MicrosoftEdge.exe
MicrosoftEdgeCP.exe
MicrosoftEdgeSH.exe
```

I think it is working perfectly now.

**Comment by Jamesits** [comment] 2018-10-19 15:34
Just contacted a Microsoft person and they said Edge content process has a special UMCI policy that your process need a Windows signature or WHQL signature to be able to inject DLLs into it. Hope this helps.

**Comment by snowie2000** [comment] 2018-10-19 15:49
Normally you need to sign the dll to make it injectable, but the edge has an exception, it can load dll from program files and system32 folder without verifying signatures. 
I don't know they removed this "feature" in the rs4 update though.

**Comment by sammilucia** [comment] 2018-10-20 00:33
So weird @Jamesits .... there's something unique about that Windows build ... we just don't know what!

**Comment by Jamesits** [comment] 2018-10-20 03:34
I captured my Windows installation overnight and started an copy in a VMWare VM. Inside the VM Edge can be started without expliclt unloading config. So I suspect one of the following differences are the cause:

* A hardware driver
* An internet connection (my system is domain joined so I cannot connect the VM to the network too)
* Some UWP programs (the change of hardware id caused all UWP programs to lose license)

Anyway I think this particular issue can now be closed. Really thanks for your help and patience.

**Comment by sammilucia** [comment] 2018-10-20 04:06
hmm interesting...

the first thing that comes to mind is Intel software guard extensions (SGX) or mayyybee Intel management engine (ME) ... both of these intercept software calls and both aren't emulated in a VM unless passthrough is enabled.

it won't be a domain/group policy because those are enforced after virtualisation.

things you can try on your physical PC:
- uninstall or disable Intel SGX driver
- uninstall or disable Intel ME driver

Thanks so much James for helping us identify the root cause of this - you've gone above and beyond!! I'll close this just so we can track our own issues, but please do keep replying to this thread if you want to work together to fix it on your physical PC 😊

**Closed by sammilucia** 2018-10-20 04:06 UTC
Labels: waiting user feedback
