### ISSUE TITLE
Windows 10 crash

### ISSUE THREAD

**Issue by Strannikus** [snowie2000/mactype#317] opened 2017-07-02 09:07 UTC
Hello! Thank you for continue developing MacType!
Since I saw new release ~week ago I had installed it. But even with v.1.2017.628 I have system crash.
The program itself starts well, I can change everything and it's going ok until I click **Start**, then system fall into BSoD with those reasons (_bluescreenview_):
```
1. ntoskrnl.exe	ntoskrnl.exe+6dff51	fffff802`a4c86000	fffff802`a550f000	0x00889000	0x59327910
					
2. hal.dll	hal.dll+62ec	fffff800`0269a000	fffff800`02716000	0x0007c000	0xcea0a646	
ndis.sys	ndis.sys+2a716	fffff80a`25a70000	fffff80a`25ba6000	0x00136000	0x167c3fea							
ntoskrnl.exe	ntoskrnl.exe+1776a9	fffff800`01e11000	fffff800`0269a000	0x00889000	0x5902843e	
```			
I tested different modes: registry, Manual and with MacTray (3×BSoD) :/
Win 10x64 1703. 15063.413

PS: (other case) sometime it still has bad kerning (i.g. in search field on Deezer: "wa" letters couple and some other). Tested on Win7.
PPS: awful fonts in LibreOffice, sorry, didn't make screenshots (Win7).

Thank you in advance for helping!

**Comment by snowie2000** [comment] 2017-07-03 01:38
First, try load modes other than registry.
Manual mode will disable mactype entirely unless you start a program with macloader which only load mactype for the specific program. Moreover, even with registry mode, ntoskrnl.exe and any system drivers won't be affect by mactype (they run in different privilege rings). You problem is caused by other software incompatibility rather than blaming mactype. Please check your system environment, especially the software related to network management.

For kerning issue, it's because Windows always arranges letters with respect to hinting, while with MacType, hinting is usually disable. And Windows GDI doesn't support sub-pixel position.

**Comment by Strannikus** [comment] 2017-07-03 16:44
Thank you, @snowie2000 
Hmm, but something crashed my system only when I click **Start** (while it runs in **Disable** by default). It happens also when other apps are closed (I've done such experiments). So what else I could check here on my PC? Excepting system default and Nod32 I don't have any other apps which may affect to network.

My only guess is that I used **DWS tool** long time ago and it changed something in system, so I still didn't have full list changes (hosts, some privacy policies and universal apps) it did.

Could you please also answer
— What was the reason of incompatibility on Win10 earlier?
— Is it possible to add somewhere in _Settings_ button Run or not to run MacType on system startup (I found only line in Task Scheduler turn on/off)? Or I poorly know the menu :)

I hope I don't have to reinstall OS just for using MacType 😅

**Comment by snowie2000** [comment] 2017-07-04 02:08
- **What was the reason of incompatibility on Win10 earlier?**

  I don't quite sure, but many of people say it's related to the incompatibility of the earlier version of easyhook. I upgraded it, and it's fine now.

- **Is it possible to add somewhere in Settings button Run or not to run MacType on system startup (I found only line in Task Scheduler turn on/off)? Or I poorly know the menu :)**

  I didn't quite get you, but I think maybe you want to know if there is a shortcut that enable/disable mactype with one click? If my guess is right, MacType Wizard is all what you need. Add a button to settings? How can I do that without Microsoft's help?

**Comment by Strannikus** [comment] 2017-07-04 11:04
That's not exactly what I meant, but I've found it in **`Set`**, pardon :) Unfortunately half of the phrase is covered by blank space.
![1](https://user-images.githubusercontent.com/26332718/27827763-9168861a-60c1-11e7-82f0-428ed9fd6938.png)

Anyway I still don't know how to solve my issue… Well, I'll live with ClearType until having aha factor or complete system clean up (as for now I'm not close to it ☺). But I will make experiments.

**Comment by snowie2000** [comment] 2017-07-04 13:55
@Strannikus Uh,  this setting is equivalent or weaker (if uac is on) than Mactype wizard (macwiz.exe). It is just historical reason to be there. After mactype wizard was introduced, this toggle is obsolete.

Always use mactype wizard to control mactype autorun option. it is way more versatile  and causes less compatible problems.

**Comment by Strannikus** [comment] 2017-07-04 20:49
@snowie2000 
Am I strange or in Mactype wizard (macwiz.exe) I'm only able to choose «preferred mode» → «preferred profile» → Finish, right?
+ Process Manager button
On some forums I saw people taking macwiz as Holy grail, and maybe it looks like I'm doing something wrong.

I turned UAC off due to its boringness :)

**Comment by snowie2000** [comment] 2017-07-05 02:09
@Strannikus Turning off UAC via control panel is not enough for Windows 10, you have to fully turn it off via gpedit.msc (Group policy) - which will make all the metro app unusable (except settings app).

Mactype wizard is nothing but an easy to use manager, it just deals with some nasty things in a convenient way.

**Comment by Strannikus** [comment] 2017-07-05 13:37
Yeah, you're right about UAC, but at least when I start usual good programs (fb2k, e.t.c.) it doesn't disturb me each time with warning message. But other factors passed me away.

Sure, wizard do its job well, but I didn't get, how could I change Autorun option there. I should go deeper :^)

**Comment by snowie2000** [comment] 2017-07-06 01:27
These loading mode listed on the Wizard page are the actual autorun strategies. e.g. Service mode registers mactype as a Windows service, which will be auto launched by Windows Service manager at startup.

**Comment by Strannikus** [comment] 2017-07-06 08:05
I guessed about that, now I know it from the first hand :)
I was sure there is special secret button, so I was looking for it as Uninstall button also. I believe some FAQ / Manual will be helpful for users (or links to good posts about it as you make it on pre-downloading window). 

Anyway, is there any guesses what I should also check on my PC to avoid OS crash? I can send you some logs or info about my system.

**Comment by sammilucia** [comment] 2018-10-12 03:49
Hi @Strannikus . i'm going to close this as I believe it's resolved in beta2, however please also see the release notes https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2 for more comments.

Please let me know if you still have problems 😊

**Closed by sammilucia** 2018-10-12 03:49 UTC
