### ISSUE TITLE
How to make it works with Vscode, Atom?

### ISSUE THREAD

**Issue by nguyenbathanh** [snowie2000/mactype#388] opened 2017-12-02 16:09 UTC
Flag `--disable-direct-write` is no longer working anymore since GDI support has been removed from Chromium. Any solutions?

**Comment by wdd817** [comment] 2017-12-21 02:38
I saw you mentioned Chromium in [https://github.com/thomasklash/vscode-mactype-hack/issues/1](url)
Personally, I recommand using Cent Browser, which still keep directwrite option on chrome://flags page.
Set directwrite off and you can get beatiful fonts ^_^

**Comment by nguyenbathanh** [comment] 2017-12-21 13:52
@wdd817 Cent Browser works but Vscode and Atom don't.

**Comment by tcbbd** [comment] 2018-01-06 07:51
@nguyenbathanh Actually the best thing we can do is to change the default parameters of DirectWrite (since skia use these default settings, and chromium use skia in turn to render fonts). It seems the default enhancedContrast (i.e. the `Contrast` option of MacType) is too low, and makes the fonts too light & blurry, so theoretically we can use a larger Contrast value so that the fonts are thicker. But the problem is that, it seems we cannot affect the rendering parameters of DirectWrite in Chrome and Chromium based apps.

**Comment by IceMan81** [comment] 2018-01-08 16:21
@tcbbd Are you saying that a higher Contrast value in DirectWrite settings will make the DirectWrite fonts look thicker?
i.e. Contrast=1.5 will be thicker than Contrast=1.0 ?

**Comment by tcbbd** [comment] 2018-01-08 16:36
@IceMan81 I'm not sure the exact effect of Contrast. But it seems firefox uses a larger Contrast value, so fonts are rendered thicker in firefox than in chrome, though both use DirectWrite. So I assume a larger Contrast can make fonts thicker.

**Comment by IceMan81** [comment] 2018-01-08 22:10
@tcbbd The contrast in mactype is different from the EnhancedContrast in FF, atleast I think it is. I don not think the Contrast here will thicken fonts like EnhancedContrast in FF
@snowie2000 Can you confirm?

**Comment by sammilucia** [comment] 2018-10-12 01:03
duplicate of #322

**Comment by sammilucia** [comment] 2018-10-12 01:17
duplicate of #401, now that Atom / Chromium / Electron only support DirectWrite

**Closed by sammilucia** 2018-10-12 01:17 UTC
Labels: duplicate
