### ISSUE TITLE
MacType deleted some text

### ISSUE THREAD

**Issue by CubicFace** [snowie2000/mactype#469] opened 2018-11-03 22:47 UTC
It's not that easy to explain.
So, some parts of text in the explorer aren't displayed and dialog boxes are empty. I think because I did something wrong on MacType (it's set on Manual). When I start MacWiz.exe, it's empty, there is only a blank window with nothing (wich is the case with MacType btw). How can I uninstall MacType?

**Comment by snowie2000** [comment] 2018-11-03 23:52
If you set mode to manual, manual here is equivalent to disabled. So mactype is actually not running at all and macwiz is a special application that can never be rendered. 

It should be a issue with your system instead of mactype. 

To uninstall mactype, try safe mode it or you could try to launch a command window and cd to the mactype folder, run the uninstaller from there.

**Comment by sammilucia** [comment] 2018-11-07 11:32
Closing as this is by design. @CubicFace please don't hesitate to let us know if that doesn't help?

**Closed by sammilucia** 2018-11-07 11:32 UTC
Labels: waiting user feedback
