### ISSUE TITLE
Fix cut outs?

### ISSUE THREAD

**Issue by Endilus** [snowie2000/mactype#374] opened 2017-11-01 15:18 UTC
Hi,

Is it possible to fix cut outs like these?
I am running version 2017_0628_0 on Windows 10 as Standalone mode and default LCD profile.

See the letter "g" and "j" in these screenshots:
![2017-11-01 16_11_19-advanced view settings_ single](https://user-images.githubusercontent.com/18008933/32281708-ee88e328-bf1f-11e7-95a3-990f1a8a0124.png)

This happens in pretty much any application, this specific screenshot is taken in Outlook 2016.

Here is another example in Skype for Business:
![2017-11-01 16_17_04-skype for business](https://user-images.githubusercontent.com/18008933/32281773-20c9de96-bf20-11e7-935a-b11f109a641d.png)

EDIT: In the first screenshot the letter "y" and "p" seems cut out also? 
Look at the text "Specify the display formats for each field".

EDIT2: It seems to look different depending on which font the application uses.
For example the same letters in Explorer looks good because the font and fontsize is different:
![image](https://user-images.githubusercontent.com/18008933/32282525-0f80b78e-bf22-11e7-8c5f-f7b4d2888341.png)

...Is it possible to tweak the profile for smaller font types to fix the cut outs?

**Comment by ssray23** [comment] 2017-11-03 13:52
I have the same issue. It would be great to see this get fixed in next build.

**Comment by absay** [comment] 2018-07-10 16:31
Was this issue ever resolved?

**Comment by ssray23** [comment] 2018-07-10 19:36
Hi,

Unfortunately, no. The problem was seen even on the very last day I had
Mactype installed on my system.

Mactype had slowed my laptop's performance to such a great degree over
time, that I had to eventually remove it.

​

With Regards,
*Suddha Satta Ray*

**Comment by sammilucia** [comment] 2018-10-01 04:53
@ssray23 the old Tray Mode slowed down MacType ... have you tried running in Service or Registry Mode? There should be no noticeable performance drop in those modes.

**Comment by sammilucia** [comment] 2018-10-01 04:57
Confirmed this ligature clipping is occurring on my Win 8.1 x64 also.

**Comment by Endilus** [comment] 2018-10-01 14:42
I never found a solution for this issue. I no longer have Windows so I don't use Mactype anymore.

**Comment by sammilucia** [comment] 2018-10-01 23:09
okay thanks @Endilus , leaving this open as a known issue.

**Comment by garoto** [comment] 2018-10-05 00:58
This reply won't be very helpful, but I (vaguely) recall snowie2000 mentioning this has to do with how GDI draw char boxes. If fixable, it probably must be super complicated to circumvent in a few lines of code.

**Comment by sammilucia** [comment] 2018-10-05 04:13
Thanks @garoto yes you're right it is to do with the box each character is 'drawn in', I believe it is complicated, let's see what @snowie2000 says when he gets back.

**Comment by sammilucia** [comment] 2018-10-19 10:16
This appears to be resolved in the latest few versions ... Closing, but please do let us know if this is still happening 😊
![image](https://user-images.githubusercontent.com/3295286/47212524-fa947080-d3df-11e8-9f0f-ad1c7df5285e.png)

**Closed by sammilucia** 2018-10-19 10:16 UTC
Labels: render defect, wip version
