### ISSUE TITLE
Mactype will not uninstall.

### ISSUE THREAD

**Issue by naomeh** [snowie2000/mactype#399] opened 2018-01-25 03:28 UTC
This issue was opened before, but you closed it with a resolution that doesn't work. https://github.com/snowie2000/mactype/issues/323

If you attempt to uninstall this program with the "uninstaller" (the installer), it merely reinstalls the program. There is no option to uninstall. I had to manually delete all of the registry files and other files of this program to finally get rid of it.

Something is wrong with the installer, or it's impossible to navigate for me / I'm doing something wrong. I changed the installer language to English, but it keeps it in Chinese. I chose every option I could, but it only tries to reinstall it again.

**Comment by usamanasir95** [comment] 2018-01-26 11:15
Just open the Installer and repair mactype. After the repair is complete, open the installer again and uninstall. This will uninstall Mactype.

**Comment by mikolajek** [comment] 2018-02-05 17:11
I second that, however a decent tip is given in the issue #133, totally worth trying.

My question is related - if I go back to the Default profile and uninstall MacType, will all display changes it disappear? The reason I'm asking is that I suspect some other display profile is applied, as my fonts look different compared to prior MacType installation. Is that possible?

**Comment by usamanasir95** [comment] 2018-02-05 17:15
Yes. All the previous changes will disappear and the font will go back to
default windows font. If the font still looks weird then goto cleartype and
set it there.

**Comment by cdl** [comment] 2018-03-02 04:53
I was running into the same issues @naomeh described - the installer was entirely in Chinese and wouldn't uninstall - it only had an option to repair the existing app. I managed to get it to uninstall some of the components by unchecking them... but this ended up breaking the installer on successive attempts, due to it being unable to find components that it previously removed.

Finally, **I managed to uninstall by [downloading the latest release installer](https://github.com/snowie2000/mactype/releases/tag/v1.2017.628.0)**, which handily gave me a dedicated button to remove the app, rather than just reinstall/repair. Clicking that worked great - it deleted it with no problem. Hopefully this helps if you're still running into this issue.

**Comment by joshuah345** [comment] 2018-08-27 19:36
the installer and macwiz dont open for me, i have rebooted already

**Comment by joshuah345** [comment] 2018-08-27 19:36
i chose registry mode

**Comment by sammilucia** [comment] 2018-08-28 05:42
Please try installing MacType 2017_0628 as a *Typical* install (not Custom). Once it has done a full install, it should then have an uninstall option in Programs and Features.

The installer needs to be redone, we will get to this as time permits, however for now avoiding a Custom install should help.

This is a duplicate of #428.

**Comment by sammilucia** [comment] 2018-08-28 05:58
Closing duplicate

**Closed by sammilucia** 2018-08-28 05:58 UTC
Labels: duplicate

**Comment by phendrome** [comment] 2018-09-09 00:29
@cdl that solution is the one that works. Launching that EXE file actually has a proper "REMOVE" button.

**Comment by PushkaCom** [comment] 2023-03-28 06:15
When I select uninstall in Windows 10 Settings, it asks to install the program, or repair / add-remove features, but there is no uninstall option, no recycling bin, and I can't unselect the root-item in the repair list - there is no way to uninstall... I'm on a company computer, I didn't install this app - I tried to install the latest version - and it installed as a 2nd app, not an upgrade, and when I uninstalled it, this un-uninstallable version was still there...

 
![image](https://user-images.githubusercontent.com/985223/228144795-99089ce5-b250-4330-889e-4366be8c3bbf.png)

![image](https://user-images.githubusercontent.com/985223/228144866-6da1e0f0-0d95-47f4-a5dc-c2a950b2984c.png)

 
![image](https://user-images.githubusercontent.com/985223/228144920-4e91068a-4b9c-4b67-ba2f-db82754ddf38.png)

 
![image](https://user-images.githubusercontent.com/985223/228145736-2a87ccca-d2be-4f6a-a940-c07a34012ffd.png)
