### ISSUE TITLE
very bad rendering of "i" and "l" in Tahoma 9pt

### ISSUE THREAD

**Issue by unalignedcoder** [snowie2000/mactype#236] opened 2017-02-21 06:50 UTC
![2017-02-21 12_47_51-mactype control panel - untitled](https://cloud.githubusercontent.com/assets/16850566/23153709/23b24642-f834-11e6-937a-229f2614aac5.jpg)

as it can be seen from pic related, hinting is enabled but at 9pt "i"s and "l"s next to each other are rendered too close. The result visible in the preview window is the best I could get playing with different options.

**Comment by snowie2000** [comment] 2017-02-21 07:02
Unfortunately, this issue is known defect and is pretty hard to solve.

The problem is basically because the Windows GDI engine doesn't support subpixel positioning. (Ref: https://msdn.microsoft.com/en-us/library/windows/desktop/dd371554(v=vs.85).aspx and https://docs.google.com/document/d/1wpzgGMqXgit6FBVaO76epnnFC_rQPdVKswrDQWyqO1M/edit)

i.e. Every letter must start from the edge of a whole pixel, not from middle from a pixel (we all knew that a typical LCD pixel consists of RGB sub-pixels).

Thus, the letter 'i' after 'l' has to be positioned to the place 1pixel away from 'l', while in Adobe Acrobat or DirectWrite, it can be placed to 1.5 pixel away which will look more naturally.

**Comment by unalignedcoder** [comment] 2017-02-21 08:34
Thanks for the info. 
I remember using gdipp back in the day and I never noticed this particular problem (actually I just reinstalled it to check and no, it doesn't have this problem).
If gdipp has worked around this problem, it might be worth looking into.

**Comment by snowie2000** [comment] 2017-02-21 08:38
Gdipp has re-implemented its own positioning system. It doesn't reply on Window GDI APIs. Which makes it displays better but brings it huge amount of compatibility problems as well. That's why I didn't do that.

**Comment by sammilucia** [comment] 2018-10-01 04:29
@snowie2000 want me to leave this open for now or wont-fix?

**Comment by snowie2000** [comment] 2018-10-11 06:04
@sammilucia It is surely a wont-fix issue. Closing.

**Closed by snowie2000** 2018-10-11 06:04 UTC
Labels: render defect

**Comment by sammilucia** [comment] 2018-10-11 06:34
agree
