### ISSUE TITLE
Font rendering in firefox 62.0 compared to Cent Browser 3.5.3.50

### ISSUE THREAD

**Issue by istir** [snowie2000/mactype#429] opened 2018-08-21 19:21 UTC
Hi!
I use MacType for few years now and it always worked more or less without any problems. Recently I wanted to switch from Cent Browser (directwrite disabled) to Firefox, but MacType font rendering is somewhat wrong. I remember that around version 55 everything worked great with right flags, but now it looks... just wrong.

I read about changing flags, so I changed following flags:
gfx.content.azure.backends=cairo 
gfx.canvas.azure.backends=cairo
gfx.direct2d.disabled=true

And the result is... somewhat wrong. Let the screenshots speak for themselves.

Reddit:
[Firefox](https://i.imgur.com/Q4UDnTI.png)
[Cent](https://i.imgur.com/evdSpE2.png)
Google:
[Firefox](https://i.imgur.com/NClobNr.png)
[Cent](https://i.imgur.com/ZqxYaGu.png)
Github:
[Firefox](https://i.imgur.com/ujzsnmC.png)
[Cent](https://i.imgur.com/7iZYMQG.png)
You get the idea.

[Firefox version](https://i.imgur.com/eUJhGPD.png)
[Cent version](https://i.imgur.com/4dTyOMZ.png)
[MacType version](https://i.imgur.com/UtUCxfv.png)

Windows 10 1607 Build 14393.2248

Could someone confirm it's problem with MacType or my machine? And maybe give some solutions?

Cheers,
istir

**Comment by istir** [comment] 2018-08-21 20:20
For now it looks like default windows rendering when installed in VMware looks better than MacType 

[Host-Windows10-MacType](https://i.imgur.com/dfFX8EP.png)
VMWare:
[Stock Windows rendering](https://i.imgur.com/KPuuUTN.png)
[MacType with direct2d.disabled=true and my .ini](https://i.imgur.com/DPsTdlP.png)


Back to Host-Windows:
after returning gfx.content.azure.backends and gfx.canvas.azure.backends to default values font [looks better](https://i.imgur.com/hmxcwnM.png) but it's still not the same as Cent Browser, fonts are lighter, even with the same fonts used in both Cent and Firefox. I probably could just mess with MacType settings but then fonts would look bold system wide.

**Comment by sammilucia** [comment] 2018-09-22 09:16
Hi @istir... the FF screenshots look like directwrite rendering to me.

can anyone else confirm the workaround is no longer working in FF 62+?

**Comment by Mahayu** [comment] 2018-09-25 05:16
I had somewhat kerning problem using Mactype in FF62..and then I returned to the directwrite.

**Comment by sammilucia** [comment] 2018-09-25 10:33
@Mahayu is it possible to post a screenshot of the kerning problems?

@snowie2000 @Mahayu I've updated the release notes of MacType to include instructions for enabling MacType/GDI in Chrome (CentBrowser) and Firefox https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

**Comment by Mahayu** [comment] 2018-09-25 10:48
I will post screenshots soon.

**Comment by sammilucia** [comment] 2018-09-25 10:58
@Mahayu yes please that would be great, thank you 😊

**Comment by Mahayu** [comment] 2018-09-25 11:06
https://github.com/Mahayu/MMConfig/blob/master/MMConfig_Clear.ini
Here is my config file. The shots should be upload tomorrow or later today. (UTC +8)

**Comment by Mahayu** [comment] 2018-09-25 13:29
![default](https://user-images.githubusercontent.com/22572355/46017172-736a1a80-c109-11e8-8be4-a4bfd4fb8a4c.png)
You may see that the word "Windows" and "Works" are weird.
![default](https://user-images.githubusercontent.com/22572355/46017275-af04e480-c109-11e8-9f49-6c81e018821a.png)
the word "malware" 

Hmm.. are they "features"?

**Comment by Mahayu** [comment] 2018-09-25 13:36
I got the point. Setting the page in 110% or higher magnification will cause mysterious kerning problems.

Setting to the 100% is OK for now.

**Comment by sammilucia** [comment] 2018-09-25 13:46
Okay interesting. I can see what you mean but I can't reproduce with my ini settings (at 100%, 110%, 120%)
![image](https://user-images.githubusercontent.com/3295286/46018291-af58ac00-c118-11e8-9f81-e4958f6ff0ec.png)

My ini file is attached if you want to try? I'm sure @snowie2000 will know! (no pressure 😜)
[No Hinting.zip](https://github.com/snowie2000/mactype/files/2415464/No.Hinting.zip)

**Comment by snowie2000** [comment] 2018-09-25 14:00
This is actually font dependent.
@Mahayu You should rather compare the screenshot with and without MacType. And to my understanding, they should behave more or less the same. But this problem should go away if you enable DirectWrite.
This is because Windows GDI does not support sub-pixel positioning. (not sub-pixel rendering, which is partially supported in W7 and got full support in W10). The left edge of a character or a letter has to be placed in an integer coordinate value (i.e. pixel perfect)
If the previous letter ends in the first sub-pixel of a whole pixel, there will be two sub-pixels gap between it and the next letter. If the previous letter ends right at the edge of that pixel, there will be no gap or a whole pixel gap between them.

Windows has made a solution for that: hinting. It will stretch the letter a bit so that the right edge of the letter can end up using a whole pixel, which may mitigate the kerning problem in some situations. You could achieve the same result by enabling hinting of MacType.

Microsoft has added the sub-pixel positioning support to DirectWrite so it's not affected.

**Comment by snowie2000** [comment] 2018-09-25 14:05
Actually, FreeType supports sub-pixel positioning, and I can put the letter from any sub-pixel of a whole pixel by calculating the correct sub-pixel arranging order (it can be complex, but it's possible). But even we did that, there is still another problem: 
You can only select text from the beginning of a pixel, which means once you select a letter that's positioned in a sub-pixel position, all the letters after it have to be rearranged which will cause a jitter. And this is impossible to avoid.

**Comment by snowie2000** [comment] 2018-09-25 14:08
What's interesting is that the hinting is really font dependent and it is written by font manufacturer by hand. It's not perfect. Sometimes, it fixes the problem, in other cases, it makes things worse.

**Comment by sammilucia** [comment] 2018-09-25 14:12
@snowie2000 so why doesn't it do it on my ini? I've also got HintingMode=1 and EnableKerning=1

**Comment by snowie2000** [comment] 2018-09-25 14:15
HintingMode=1 means disabling hinting.
EnableKerning is somewhat mystery... I've never touched any code about it. Someone says it's buggy.

**Comment by snowie2000** [comment] 2018-09-25 14:52
I'll test Mahayu's profile tomorrow to see if it makes any difference in my environment.
And about the kerning setting, if you enable that setting, MacType will use the information returned by GetKerningPairs or FT_GET_KERNING. Most fonts, they just simply don't support kerning.
So this setting may work, but I never had a chance to test it in real life.

**Comment by istir** [comment] 2018-09-25 14:56
Not sure why is that but when I had it set to basically anything other than direct2d1.1,cairo,skia it didn't work (like in my top post), but after setting it up like in updated readme it works great!

I created a gif showing different modes, feel free to use it somewhere!
https://i.imgur.com/6K1DTWN.gifv

**Comment by sammilucia** [comment] 2018-09-25 15:13
@istir hmm I don't know! yay I'm glad it's working for you now 😊

**Comment by snowie2000** [comment] 2018-09-26 06:05
![qq 20180926140207](https://user-images.githubusercontent.com/11767189/46060204-ebc9ed80-c194-11e8-8bef-d02e7a36c1f5.png)
@Mahayu This is my result. (My chrome is not at the zoom ratio of 110%, so you are definitely using a monitor with HiDPI)
As you can see, my texts didn't have the same problem because apparently, we are using different fonts for alphabets.

**Comment by IceMan81** [comment] 2018-09-26 06:09
@snowie2000 would you mind sharing your ini file?

**Comment by snowie2000** [comment] 2018-09-26 06:36
I was using the config provided here: https://github.com/snowie2000/mactype/issues/429#issuecomment-424300900

**Comment by IceMan81** [comment] 2018-09-26 06:39
In that case, would you mind sharing the ini file you use on your Windows?

**Comment by snowie2000** [comment] 2018-09-26 06:41
It's not about the profile I'm using, it's about the font you're using in your browser.

**Comment by sammilucia** [comment] 2018-10-01 06:05
I'm about to close this thread 'cause it's not going anywhere 😜 ... Is there anything else left to be done?

**Comment by sammilucia** [comment] 2018-10-11 14:47
Closing as no further action. Please let me know if that's wrong

**Closed by sammilucia** 2018-10-11 14:47 UTC
Labels: waiting user feedback
