### ISSUE TITLE
2017.628 版本 打开Directwrite无效

### ISSUE THREAD

**Issue by vrships** [snowie2000/mactype#338] opened 2017-07-14 18:56 UTC
以前是通过日本人补丁实现DW渲染和调教的，效果还不错，就是会和所有可以加载字幕的播放器冲突。
现在升级了最新版，发现DW怎么也打不开。我是添加了directwrite=1 条目的，注册表加载。

ini文件中的DW字段究竟应该如何写啊, 我翻来翻去也没看到这些信息，只好从别人改好的ini里复制粘贴过来一部分。但是怎样都没有效果。

比如我在下面最后部分手动添加上了一系列DW参数，是这样用吗？

[General]
Name=FT Opt
Icon=..\mactray.exe,012
HookChildProcesses=1
HintingMode=1
AntiAliasMode=2
shadow=0,0,0,0x0,0,0x0
MaxHeight=150
UseMapping=0
FontLink=1
FontSubstitutes=0
WidthMode=0
FontLoader=0
BolderMode=0
GammaMode=0
GammaValue=1.7
RenderWeight=1.0
Contrast=1.0
TextTuning=0
NormalWeight=0
BoldWeight=0
ItalicSlant=0
LcdFilter=1
LoadOnDemand=1
TextTuning=0
TextTuningR=0
TextTuningG=0
TextTuningB=0
CacheMaxFaces=64
CacheMaxSizes=64
CacheMaxBytes=52428800
EnableKerning=0
MaxBitmap=0
DirectWrite=1
HintSmallFont=0
;CacheMaxBytes=10485760

[ExcludeModule]

[Experimental@Firefox.exe]
ClipBoxFix=1
[UnloadDll]
[exclude]
[FontSubstitutes]
[Individual]
[ExcludeSub]

[DirectWrite]
;0 = DWRITE_RENDERING_MODE_DEFAULT
; Specifies that the rendering mode is determined automatically based on the font and size.
;1 = DWRITE_RENDERING_MODE_ALIASED
; Specifies that no antialiasing is performed. Each pixel is either set to the foreground
; color of the text or retains the color of the background.
;2 = DWRITE_RENDERING_MODE_GDI_CLASSIC
; Specifies that antialiasing is performed in the horizontal direction and the appearance
; of glyphs is layout-compatible with GDI using CLEARTYPE_QUALITY. Use DWRITE_MEASURING_MODE_GDI_CLASSIC
; to get glyph advances. The antialiasing may be either ClearType or grayscale depending on
; the text antialiasing mode.
;3 = DWRITE_RENDERING_MODE_GDI_NATURAL
; Specifies that antialiasing is performed in the horizontal direction and the appearance
; of glyphs is layout-compatible with GDI using CLEARTYPE_NATURAL_QUALITY. Glyph advances
; are close to the font design advances, but are still rounded to whole pixels. Use
; DWRITE_MEASURING_MODE_GDI_NATURAL to get glyph advances. The antialiasing may be either
; ClearType or grayscale depending on the text antialiasing mode.
;4 = DWRITE_RENDERING_MODE_NATURAL
; Specifies that antialiasing is performed in the horizontal direction. This rendering
; mode allows glyphs to be positioned with subpixel precision and is therefore suitable
; for natural (i.e., resolution-independent) layout. The antialiasing may be either
; ClearType or grayscale depending on the text antialiasing mode.
;5 = DWRITE_RENDERING_MODE_NATURAL_SYMMETRIC
; Similar to natural mode except that antialiasing is performed in both the horizontal
; and vertical directions. This is typically used at larger sizes to make curves and
; diagonal lines look smoother. The antialiasing may be either ClearType or grayscale
; depending on the text antialiasing mode.
;6 = DWRITE_RENDERING_MODE_OUTLINE
; Specifies that rendering should bypass the rasterizer and use the outlines directly.
; This is typically used at very large sizes.
RenderingMode=5

;This setting enhances the edge of font
;if you tune it too high, you will get a colored edge.
;if you tune it too low, the font will become blurry.
;Min: 0.0625
;Max: 10.0
Contrast=1.0

;Determine the degree directwrite applies anti-alias to the font outline.
;Min: 0
;Max: 1.0
ClearTypeLevel=1.0

;For DirectWrite, if it is undefined, the gammavalue will be calculated automatically
;with respect to the gammavalue in General Section.
GammaValue=1.8

是不是日本人的补丁要完全清楚干净才行？要去system32和sysWOW64中把easyhook都删掉嘛？

十分感谢！

**Comment by snowie2000** [comment] 2017-07-15 11:59
配置文件看上去并没有什么问题……我在我自己的系统上测试过了，没有发现任何问题

**Comment by czy1996** [comment] 2017-08-27 03:53
我有同样的问题，而且是重新安装系统之后才安装的新版 Mactype，百思不得其解

**Comment by sammilucia** [comment] 2018-10-01 05:47
@vrships @czy1996 The ini parser in the newest mactype has been rewritten. Could you please try: 
- removing all the comments from the ini file and see if this helps
- checking your regional settings are set to use '.' (period) decimals and not ',' (comma) decimals

This is a duplicate of another issue but I can't find it right now!

@snowie2000

**Comment by sammilucia** [comment] 2018-10-11 14:44
Closing as abandoned. Please try my comments and let us know if you still have the problem

**Closed by sammilucia** 2018-10-11 14:44 UTC
Labels: waiting user feedback
