### ISSUE TITLE
Bit Defender 2018 Troubleshooting Info

### ISSUE THREAD

**Issue by RitzyBusiness** [snowie2000/mactype#353] opened 2017-08-10 19:39 UTC
Bit defender was reading a false positive on the mactype hooks and causing explorer.exe to crash as it attempted to quarantine it.  (Rather then attacking specific mactype dll's or executables)  Has the potential to make an attempt to delete explorer.exe and rundll.exe from your system.  Other symptoms are BSOD  requiring safemode reboot.

If you find yourself in this situation, Shift+Left Click restart your PC from the login screen which will unlock the option to enable safe mode boot.  Either use the 2018 Bit Defender Uninstall tool or run mactype tray and set to manual.

****Nothing works********** Has to be fixed by Bit Defender most likely.

**Comment by Gino** [comment] 2017-09-29 11:26
#364 I've added all the files to the Bitdefender whitelist, unfortunately this still got problems with hooks.

**Comment by RitzyBusiness** [comment] 2017-09-29 21:26
Yea unfortunately I am having problems as well thats why I closed this out.  It worked for like a day and then kind of failed.

Their ideal is to reinstall BD2018 (which I have a few times already) and send them a log but the new ATC likes to delete/disinfect legitimate executable and drivers leaving a mess on my PC.  No way to stop it from doing so, so its worst then the malware it purports to prevent.  

So if/when it is fixed I wont be able to test it myself. Of course without mactype running it does nothing of the sort.

**Comment by sammilucia** [comment] 2018-10-01 05:36
Duplicate of #361, @RitzyBusiness please see my comments there if you're still having the conflict with BitDefender 😊.

**Closed by sammilucia** 2018-10-01 05:36 UTC
Labels: duplicate, wontfix
