### ISSUE TITLE
CJK fonts of not rendered correctly in LibreOffice v5.3.

### ISSUE THREAD

**Issue by Explorare** [snowie2000/mactype#334] opened 2017-07-11 16:12 UTC
##### System environment
Windows 10 Enterprise 15063.413 (x64)
MacType v1.2017.628.0
LibreOffice v5.3.4.2 (x64)

##### Issue
CJK fonts of not rendered correctly in LibreOffice v5.3.

![image](https://user-images.githubusercontent.com/5090766/28078070-3665e9b2-6696-11e7-8d7a-1da7e8a32135.png)

![image](https://user-images.githubusercontent.com/5090766/28078085-466a7ee0-6696-11e7-8853-f50218b572e8.png)

It seems that the MacType didn't render LibreOfffice's UI?

It works well with Calibre.

![image](https://user-images.githubusercontent.com/5090766/28078152-824423ee-6696-11e7-947e-5425b901d47d.png)

Here's my config file:
https://gist.github.com/Explorare/b740a1efa7efdc235ac2fb52c413736d

**Comment by sammilucia** [comment] 2018-10-12 03:52
@Explorare those fonts you've marked are being rendered with DirectWrite. Weird for them to use DW just for those... or maybe it's the controls they're using from their libraries/IDE.

Because this is related to the DW question, I'm going to mark this as a duplicate of #401. Improving DW is an ongoing question for that issue

**Closed by sammilucia** 2018-10-12 03:52 UTC
Labels: duplicate
