### ISSUE TITLE
Error Ordinal 345 when running Electron Apps

### ISSUE THREAD

**Issue by kuspoes** [snowie2000/mactype#695] opened 2020-10-23 02:38 UTC
Using latest MacType release,

Windows throw  Error Ordinal 345 every time I run electron apps after installing MacType. 
Uninstalling MacType solved this error.

Is there a way to keep MacType running without this problem?

Thanks You.

**Comment by snowie2000** [comment] 2020-10-23 02:42
duplicate of #488 
Please comment there. Thanks.

**Closed as completed by snowie2000** 2020-10-23 02:42 UTC
