### ISSUE TITLE
Paint .net compatibility issues

### ISSUE THREAD

**Issue by Craftplacer** [snowie2000/mactype#412] opened 2018-03-31 15:02 UTC
I've sent a crash report to the paint .net developers which they responded that this is a issue that the MacType team should fix.
> This is probably caused by MacType, which is known to cause Paint.NET to crash. If you disable or uninstall it, then Paint.NET will work again.
> 
> Please report this to the MacType team so they can fix it.
> 
> -Rick Brewster
> 
> On Fri, Mar 30, 2018 at 8:02 AM, Craftplacer wrote:
> `
> This text file was created because paint.net crashed. Please e-mail this to crashlog4@getpaint.net so we can diagnose and fix the problem.
> 
> 
> 
> Application version: paint.net 4.0.21 (Final 4.21.6589.7045)
> 
> Time of crash: 30/03/2018 15:00:23
> 
> Application uptime: 15:57:57.8942419
> 
> Application state: Running 
> 
> Working set: 67.132 KiB
> 
> Handles and threads: 1037 handles, 32 threads, 228 gdi, 268 user
> 
> Install type: Classic
> 
> Application directory: A:\Software\paint.net
> 
> Current directory: A:\Software\paint.net
> 
> Install directory: A:\Software\paint.net
> 
> OS Version: Windows 10 Pro 10.0.16299.0 x64 (0x30)
> 
> .NET version: CLR 4.0.30319.42000 x64
> 
> Processor: "Intel(R) Core(TM) i3 CPU         550  @ 3.20GHz" @ ~3192MHz (2C/4T, DEP, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2)
> 
> Physical memory: 3959 MB
> 
> Video card: ATI Radeon HD 4600 Series (v:1002, d:9498, r:0), Microsoft Basic Render Driver (v:1414, d:8C, r:0)
> 
> Hardware acceleration: True (default: True)
> 
> UI animations: True
> 
> UI DPI: 96,00 dpi (1,00x scale)
> 
> UI theme: VisualStyleClass=Aero, EffectiveTheme=Aero, DWM=yes, AeroColorScheme=Dark, ThemeFileName=Aero.msstyles
> 
> Updates: True, 15/03/2018
> 
> Locale: pdnr.c: en-US, hklm: en-US, hkcu: en-US, cc: en-DE, cuic: en-US
> 
> Flags: EnableSmoothMouseInput=False
> 
> 
> 
> Exception details:
> 
> System.ArgumentException: ..\Direct2D\D2DRenderTarget.cpp (286) : hr = m_pRenderTarget->EndDraw(&d2dTag1, &d2dTag2); (PaintDotNet.Controls.HeadingLabel)
> 
>    at PaintDotNet.Interop.InteropErrorInfo.ThrowIfError() in D:\src\pdn\src\Base\Interop\InteropErrorInfo.cs:line 89
> 
>    at PaintDotNet.SystemLayer.Native.x64.NativeUtilities.ThrowOnErrorImpl(Int32 hr, SByte* szHr, IUnknown* pFxErrorInfo)
> 
>    at PaintDotNet.SystemLayer.Native.x64.Direct2D.D2DRenderTarget.EndDraw(Tag& tag1, Tag& tag2)
> 
>    at PaintDotNet.Controls.Direct2DControlHandler.RelayGdiPaintImpl(GdiPaintContext ctx) in D:\src\pdn\src\Framework\Controls\Direct2DControlHandler.cs:line 667
> 
>    at PaintDotNet.Controls.Direct2DControlHandler.RelayGdiPaint(GdiPaintContext ctx) in D:\src\pdn\src\Framework\Controls\Direct2DControlHandler.cs:line 483
> 
>    at PaintDotNet.Controls.Direct2DControl.OnGdiPaint(GdiPaintContext ctx) in D:\src\pdn\src\Framework\Controls\Direct2DControl.cs:line 347
> 
>    at PaintDotNet.SystemLayer.GdiPaintHandler.OnWmPaint(Message& m) in D:\src\pdn\src\SystemLayer\GdiPaintHandler.cs:line 184
> 
>    at PaintDotNet.SystemLayer.GdiPaintHandler.RelayWndProc(Message& m) in D:\src\pdn\src\SystemLayer\GdiPaintHandler.cs:line 233
> 
>    at PaintDotNet.SystemLayer.GdiPaintControl.WndProc(Message& m) in D:\src\pdn\src\SystemLayer\GdiPaintControl.cs:line 130
> 
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> 
> Managed assemblies: 
> 
>     mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll
> 
>     PaintDotNet, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.exe
> 
>     PaintDotNet.Base, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Base.dll
> 
>     WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll
> 
>     System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll
> 
>     System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
> 
>     System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
> 
>     PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll
> 
>     PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll
> 
>     System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
> 
>     PaintDotNet.Core, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Core.dll
> 
>     PaintDotNet.SystemLayer, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.SystemLayer.dll
> 
>     PaintDotNet.Framework, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Framework.dll
> 
>     PaintDotNet.Resources, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Resources.dll
> 
>     PaintDotNet.Data, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Data.dll
> 
>     PaintDotNet.Effects, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.Effects.dll
> 
>     System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll
> 
>     System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll
> 
>     PaintDotNet.SystemLayer.Native.x64, Version=4.21.6589.7045, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\PaintDotNet.SystemLayer.Native.x64.dll
> 
>     System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 @ C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll
> 
>     Vandermotten.PaintDotNetEffects.Blurs, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.Blurs.dll
> 
>     Vandermotten.PaintDotNetEffects.ColorAccent, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.ColorAccent.dll
> 
>     Vandermotten.PaintDotNetEffects, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.dll
> 
>     Vandermotten.PaintDotNetEffects.DropShadow, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.DropShadow.dll
> 
>     Vandermotten.PaintDotNetEffects.Duotones, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.Duotones.dll
> 
>     Vandermotten.PaintDotNetEffects.FadeEdge, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.FadeEdge.dll
> 
>     Vandermotten.PaintDotNetEffects.Gradient, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.Gradient.dll
> 
>     Vandermotten.PaintDotNetEffects.Grid, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.Grid.dll
> 
>     Vandermotten.PaintDotNetEffects.Monochromes, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.Monochromes.dll
> 
>     Vandermotten.PaintDotNetEffects.ObjectAlign, Version=3.8.0.0, Culture=neutral, PublicKeyToken=null @ A:\Software\paint.net\Effects\Vandermotten.PaintDotNetEffects.ObjectAlign.dll
> 
> 
> 
> Native modules: 
> 
>     A:\Software\paint.net\PaintDotNet.exe, version=4.21.6589.7045
> 
>     C:\WINDOWS\SYSTEM32\ntdll.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\MSCOREE.DLL, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\KERNEL32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\KERNELBASE.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\ADVAPI32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\msvcrt.dll, version=7.0.16299.125 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\sechost.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\RPCRT4.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\System32\SHLWAPI.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\combase.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\ucrtbase.dll, version=10.0.16299.248 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\bcryptPrimitives.dll, version=10.0.16299.98 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\GDI32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\gdi32full.dll, version=10.0.16299.98 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\msvcp_win.dll, version=10.0.16299.248 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\USER32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\win32u.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\IMM32.DLL, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\kernel.appcore.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\VERSION.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll, version=12.00.52519.0 built by: VSWINSERVICING
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\mscorlib\a39512bde949dc065175a3be81664375\mscorlib.ni.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\System32\ole32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\uxtheme.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System\d41b66a8a5dde18b54c79b7b42b5c951\System.ni.dll, version=4.7.2556.0 built by: NET471REL1
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Core\2e6ad675e5f9e923284877dd42f58f75\System.Core.ni.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\WindowsBase\61b21f1b81bf7c3a322dca471cf7d4b9\WindowsBase.ni.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\SYSTEM32\CRYPTSP.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\rsaenh.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\bcrypt.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\CRYPTBASE.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Drawing\82c5a5ae4522e2125b6f262b52f5d7ca\System.Drawing.ni.dll, version=4.7.2556.0 built by: NET471REL1
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PresentationCore\b3c6aa686205a6f7612ec0d9b028b83d\PresentationCore.ni.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\ea631a4b33eedc310a6be79b4db1a013\PresentationFramework.ni.dll, version=4.7.2633.0
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet.Base\a2c4da426c85d85d0740d2411e007db4\PaintDotNet.Base.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\810582c1bd43c1e06ab47c66e98993bd\System.Windows.Forms.ni.dll, version=4.7.2556.0 built by: NET471REL1
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet500b2e4f#\c17e3e574e04e89c809ca4bc6edf954e\PaintDotNet.SystemLayer.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet.Core\a8d8bdecbfc9f0fd00126648cc89ed02\PaintDotNet.Core.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet26779e70#\beb773e3eb636ed16a8b9dfa2765e332\PaintDotNet.Resources.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet7afaaa15#\51486bd34df08ee13c9a4da684348a5e\PaintDotNet.Framework.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet.Data\4fc3ed9cda5bfff3abf57aef56827091\PaintDotNet.Data.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet.Effects\2c2e141e66e2803d46817f4633d3771f\PaintDotNet.Effects.ni.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNet\e83fbee9304d739ee9cd5c5921335347\PaintDotNet.ni.exe, version=4.21.6589.7045
> 
>     C:\WINDOWS\SYSTEM32\dwrite.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\System32\OLEAUT32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\MSVCP120_CLR0400.dll, version=12.00.52519.0 built by: VSWINSERVICING
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\System32\shell32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\cfgmgr32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\shcore.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\windows.storage.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\powrprof.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\profapi.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\msvcp140.dll, version=14.13.26020.0 built by: VCTOOLSREL
> 
>     C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll, version=14.13.26020.0 built by: VCTOOLSREL
> 
>     C:\WINDOWS\SYSTEM32\vcomp140.dll, version=14.13.26020.0 built by: VCTOOLSREL
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Configuration\303d455e2eac7725610cd55c8170ba00\System.Configuration.ni.dll, version=4.7.2556.0 built by: NET471REL1
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xml\2f52ca6330aa92554abf777e2b7d6783\System.Xml.ni.dll, version=4.7.2612.0 built by: NET471REL1LAST_B
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\WINDOWS\System32\MSCTF.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\PaintDotNetc8826574#\bcc466a1b7642d74484af96549aecdc6\PaintDotNet.SystemLayer.Native.x64.ni.dll, version=4.21.6589.7045
> 
>     A:\Software\paint.net\PaintDotNet.SystemLayer.Native.x64.dll, version=4.21.6589.7045
> 
>     C:\WINDOWS\SYSTEM32\PROPSYS.dll, version=7.0.16299.98 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.16299.309_none_46bac7a9edf0e4df\gdiplus.dll, version=10.0.16299.309 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\dxgi.dll, version=10.0.16299.98 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\dwmapi.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\clbcatq.dll, version=2001.12.10941.16384 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\UIAnimation.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.16299.309_none_15cfd4c4935e6b11\comctl32.dll, version=6.10 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.16299.309_none_8875ce284abe80d8\comctl32.dll, version=6.10 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\WindowsCodecs.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\wtsapi32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\WINSTA.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\d2d1.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\CRYPT32.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\MSASN1.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\d3d11.dll, version=10.0.16299.248 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\D3D10Warp.dll, version=10.0.16299.309 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\USERENV.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\dataexchange.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\dcomp.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\twinapi.appcore.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\RMCLIENT.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\assembly\NativeImages_v4.0.30319_64\System.Xaml\822b9f698ab3dacaf2dd6a47a1199a0e\System.Xaml.ni.dll, version=4.7.2633.0 built by: NET471REL1LAST_C
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll, version=14.7.2556.0 built by: NET471REL1
> 
>     C:\WINDOWS\SYSTEM32\winmm.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\winmmbase.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\aticfx64.dll, version=8.17.10.1129
> 
>     C:\WINDOWS\SYSTEM32\atiuxp64.dll, version=8.14.01.6264
> 
>     C:\WINDOWS\SYSTEM32\atidxx64.dll, version=8.17.10.0436
> 
>     C:\WINDOWS\System32\TextInputFramework.dll, version=10.0.16299.248 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\CoreUIComponents.dll, version=10.0.16299.15
> 
>     C:\WINDOWS\System32\CoreMessaging.dll, version=10.0.16299.15
> 
>     C:\WINDOWS\SYSTEM32\ntmarta.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\wintypes.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\system32\explorerframe.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\edputil.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrcompression.dll, version=4.7.2556.0 built by: NET471REL1
> 
>     A:\Software\MacType\MacType64.dll, version=1.0.0.1
> 
>     A:\Software\MacType\Easyhk64.dll, version=2.7.0.0
> 
>     A:\Software\MacType\MacType64.Core.dll, version=1.2017.628.0
> 
>     C:\WINDOWS\System32\SetupApi.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\SYSTEM32\DEVOBJ.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\WINTRUST.dll, version=10.0.16299.309 (WinBuild.160101.0800)
> 
>     C:\WINDOWS\System32\psapi.dll, version=10.0.16299.15 (WinBuild.160101.0800)
> 
> ------------------------------------------------------------------------------
> `

**Comment by snowie2000** [comment] 2018-03-31 15:52
Thank you for your feedback.
Looks like you're running paint.net on Windows 10 which will be hard for me
to debug since I don't have a computer fully compatible with Windows 10.
Anyway I'll still to reproduce your problem on my Windows 7 machine.
Its quite clear that the problem is from the direct2d hooking, so obviously
the first solution you can try is disabling the directwritr support from
MacType by setting directwrite to 0. I believe the paint.net should not
crash anymore. If you do need the directwrite support you can set an
exception for paint.net by using the @ grammar to only disable dw support
only for paint.net.

**Comment by sammilucia** [comment] 2018-08-20 12:04
Hi @Craftplacer ... thanks again for reporting this, and for working with Microsoft on the issue! In your mactype .ini file that you're using please add 
PaintDotNet.exe under the [UnloadDll] section of the ini and restart your computer.

If you can do that for now, I'm going to close this and add it to issue #426 so we can keep all the known problems together for testing.

**Closed by sammilucia** 2018-08-20 12:04 UTC
Labels: duplicate
