### ISSUE TITLE
Win 1803使用MacType开机黑屏无法进入系统

### ISSUE THREAD

**Issue by TianLi-520** [snowie2000/mactype#419] opened 2018-05-18 03:55 UTC
家里两台电脑，3代酷睿平台没有问题，7代酷睿升级后开机就黑屏，只有转圈的鼠标，无法进入系统，安全模式删除MacType就好了

**Comment by guikarist** [comment] 2018-05-24 14:15
Same like me. #421

**Comment by guikarist** [comment] 2018-09-19 00:49
终于要更新了

**Comment by sammilucia** [comment] 2018-10-01 05:52
Closing as duplicate of #420 

@TianLi-520 @guikarist please see the latest release notes for how to fix this. Let us know if you still have problems 😊 https://github.com/snowie2000/mactype/releases/tag/1.2018.917.0-beta2

**Closed by sammilucia** 2018-10-01 05:52 UTC
Labels: duplicate
