### ISSUE TITLE
win 10 

### ISSUE THREAD

**Issue by MishGa** [snowie2000/mactype#369] opened 2017-10-20 12:38 UTC
It does not start on win 10 pro 1709.

**Comment by drxt** [comment] 2017-10-23 11:50
Can anyone confirm if it works on 1709 on tray mode? Also DirectWrite injection?

**Comment by hyrious** [comment] 2017-10-23 15:08
@drxt I can confirm it works well on 1709 with tray mode as I clean-installed a week ago.

**Comment by MishGa** [comment] 2017-10-23 15:51
Now reinstalled and started. Works through the registry.

**Comment by vrships** [comment] 2017-10-23 19:22
I had upgraded to 1709 and the system kept crashing due to display driver failure until I disabled Mactype. I was always running with the Japanese patch. I uninstalled it and reinstall without the Japanese patch and now it is working fine in registry mode. But the DW feature is almost gone. Only the settings panel are mactype enabled. Start Menu and other UWP interfaces have no mactype effect at all.

I am considering apply the Japanese patch again but I am afraid it will cause crashing.

**Comment by snowie2000** [comment] 2017-10-24 00:59
You have to install mactype to the default location to enable all the
directwrite support.

**Comment by vrships** [comment] 2017-10-24 17:40
> You have to install mactype to the default location to enable all the
directwrite support.

Yeah I always keep it installed in the default folder: program files/mactype. Still DW barely works.

**Comment by drxt** [comment] 2017-10-25 23:23
So I've installed Mactype on a fresh install of 1709, and I've noticed two separate issues:

- Only Windows Store app that works with Mactype Direct Write injection is the Settings app. Nothing else gets Mactype applied.
- Microsoft Office 2016 doesn't get affected by Mactype either while Visual Studio 2017 does.

**Comment by vrships** [comment] 2017-11-01 11:00
@drxt 
I am having exactly the same problems. Almost no UWP app works except Settings. I tried adding the [direct2D] lines into the ini file but that did not work either.

**Comment by Thesharing** [comment] 2017-11-07 18:04
Have met the same problem. MacType doesn't render the start menu or UWP Apps like Microsoft Edge. I tried uninstall it and then reinstall it but it didn't fix the problem.

**Comment by sammilucia** [comment] 2018-08-28 06:38
Hiya, can you please confirm if MacType is working correctly with the latest DLL files here: http://www.mactype.net/station/MacType_CTP_171017.rar

**Comment by sammilucia** [comment] 2018-10-01 05:02
Closed as unresponded.

**Closed by sammilucia** 2018-10-01 05:02 UTC
Labels: directwrite
